// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/argoproj/gitops-engine/pkg/health

package health

_#hpaCondition: {
	Type:    string
	Reason:  string
	Message: string
	Status:  string
}
