// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/pod-security-admission/api

// Package api contains constants and helpers for PodSecurity admission label keys and values
package api
