// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/pod-security-admission/api

package api

#LevelVersion: Level: #Level

#Policy: {
	Enforce: #LevelVersion
	Audit:   #LevelVersion
	Warn:    #LevelVersion
}
