// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/argoproj/gitops-engine/pkg/utils/kube

package kube

// ResourceOperations provides methods to manage k8s resources
#ResourceOperations: _
