// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go istio.io/client-go/pkg/apis/security/v1beta1

// Package has auto-generated kube type wrappers for raw types.
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package
// +groupName=security.istio.io
package v1beta1
