// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go istio.io/client-go/pkg/apis/security/v1beta1

package v1beta1

// Package-wide consts from generator "register".
#GroupName: "security.istio.io"
